project 'WorkdayArrangement.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WorkdayArrangement' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WorkdayArrangement

  target 'WorkdayArrangementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WorkdayArrangementUITests' do
    inherit! :search_paths
    # Pods for testing
  end
#   pod 'Realm'            ,'3.13.1'
  pod 'CRGradientNavigationBar'            ,'0.3.2'
  pod 'SVProgressHUD'            ,'2.2.5'
  pod 'ActionSheetPicker-3.0'            ,'2.3.0'
end
